image: node:latest

before_script:
  - npm config set //${CI_SERVER_HOST}/api/v4/projects/29926955/packages/npm/:_authToken ${CI_JOB_TOKEN}
  - npm install

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm test

build:
  stage: deploy
  script:
    - npm run build
    - npm publish

  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - when: manual
